apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/etc/promtail/promtail-config.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/promtail
      volumes:
        - name: config-volume
          configMap:
            name: promtail-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail-config.yaml: |
    scrape_configs:
      - job_name: system-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: node-logs
        pipeline_stages:
          - docker: {}
          - drop:
              regex: ".*health_check.*"
      # Add more scrape_configs or pipelines as needed

